# HMS Networks; Americas
# Build Test Action for Maven-based Ewon ETK Projects
# Version: 3.0.1
# Date: April 2, 2024
# Modifications:
# - Changed the JDK version to 11 (for Ignition SDK projects)
#
# This action is configured to automatically run when a push
# is made to the `main` branch or a pull request for the `main`
# branch.

name: Build Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11
          cache: 'maven'

      - name: Package Java Files With Maven
        run: mvn package -f pom.xml