# HMS Networks; Americas
# Code Format Test Action for Maven-based Ewon ETK Projects
# Version: 3.0.0
# Date: February 8, 2024
#
# This action is configured to automatically run when a push
# is made to the `main` branch or a pull request for the `main`
# branch.

name: Code Format Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-format-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Test Code Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--dry-run --skip-sorting-imports --set-exit-if-changed"